# Network
MODEL_USE: mfb
HIGH_ORDER: False # True for MFH, False for MFB
HIDDEN_SIZE: 512
MFB_K: 5
MFB_O: 1000
LSTM_OUT_SIZE: 1024
DROPOUT_R: 0.1
I_GLIMPSES: 2
Q_GLIMPSES: 2

# Features
WORD_EMBED_SIZE: 300
FRCN_FEAT_SIZE: 2048